version: "3"
services:
  pycharm-ide:
    image: hamerhed:tensorflow-cuda12-ide
    container_name: ml-ide
    volumes: 
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ~/ml-ide:/home/user
      - ~/workspace-ml:/home/user/workspace
    environment:
      - DISPLAY
    tty: true
    network_mode: host
    command: bash -c "rm -f ~/.config/spyder-py3/spyder.lock && spyder"