version: "3"
services:
  code-studio-ide:
    image: hamerhed:tensorflow-cuda12-ide
    container_name: ml-ide
    volumes: 
      - ~/ml-ide:/home/user
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ~/workspace-ml:/home/user/workspace
    environment:
      - DISPLAY
    tty: true
    network_mode: host
    command: "/usr/share/code/code --no-sandbox"